### ISSUE TITLE
Doesn't work with Symfony3

### ISSUE THREAD

**Issue by bjoernfal** [robbiepaul/zbar-qrdecoder#4]
If your're using Symfony3, then composer won't install it, because of the requirements "symfony/process 2.*".

Should work with "symfony/process 3.*".

**Comment by robbiepaul** [comment]
Thanks for reporting this. Even though there's no breaking changes between `symphony/process` `2.x` and `3.x` because it's a major version change I've tagged my package as a new major version `2.0.0` to ensure backwards compatibility.

Please update your `composer.json` to:

``` js
"robbiep/zbar-qrdecoder": "^2.0"
```

**Comment by bjoernfal** [comment]
Thanks, it works!
